CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Genres" (
    "GenreID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("GenreID")
);

CREATE TABLE "Languages" (
    "LanguageID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("LanguageID")
);

CREATE TABLE "Tags" (
    "TagID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("TagID")
);

CREATE TABLE "Users" (
    "UserID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "RegistrationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserID")
);

CREATE TABLE "UserProfiles" (
    "UserID" integer NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Country" text NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("UserID"),
    CONSTRAINT "FK_UserProfiles_Users_UserID" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE CASCADE
);

CREATE TABLE "ProfileGenres" (
    "UserID" integer NOT NULL,
    "GenreID" integer NOT NULL,
    "UserProfileUserID" integer NOT NULL,
    CONSTRAINT "PK_ProfileGenres" PRIMARY KEY ("UserID", "GenreID"),
    CONSTRAINT "FK_ProfileGenres_Genres_GenreID" FOREIGN KEY ("GenreID") REFERENCES "Genres" ("GenreID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileGenres_UserProfiles_UserProfileUserID" FOREIGN KEY ("UserProfileUserID") REFERENCES "UserProfiles" ("UserID") ON DELETE CASCADE
);

CREATE TABLE "ProfileLanguages" (
    "UserID" integer NOT NULL,
    "LanguageID" integer NOT NULL,
    "UserProfileUserID" integer NOT NULL,
    CONSTRAINT "PK_ProfileLanguages" PRIMARY KEY ("UserID", "LanguageID"),
    CONSTRAINT "FK_ProfileLanguages_Languages_LanguageID" FOREIGN KEY ("LanguageID") REFERENCES "Languages" ("LanguageID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileLanguages_UserProfiles_UserProfileUserID" FOREIGN KEY ("UserProfileUserID") REFERENCES "UserProfiles" ("UserID") ON DELETE CASCADE
);

CREATE TABLE "ProfileTags" (
    "UserID" integer NOT NULL,
    "TagID" integer NOT NULL,
    "UserProfileUserID" integer NOT NULL,
    CONSTRAINT "PK_ProfileTags" PRIMARY KEY ("UserID", "TagID"),
    CONSTRAINT "FK_ProfileTags_Tags_TagID" FOREIGN KEY ("TagID") REFERENCES "Tags" ("TagID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileTags_UserProfiles_UserProfileUserID" FOREIGN KEY ("UserProfileUserID") REFERENCES "UserProfiles" ("UserID") ON DELETE CASCADE
);

CREATE INDEX "IX_ProfileGenres_GenreID" ON "ProfileGenres" ("GenreID");

CREATE INDEX "IX_ProfileGenres_UserProfileUserID" ON "ProfileGenres" ("UserProfileUserID");

CREATE INDEX "IX_ProfileLanguages_LanguageID" ON "ProfileLanguages" ("LanguageID");

CREATE INDEX "IX_ProfileLanguages_UserProfileUserID" ON "ProfileLanguages" ("UserProfileUserID");

CREATE INDEX "IX_ProfileTags_TagID" ON "ProfileTags" ("TagID");

CREATE INDEX "IX_ProfileTags_UserProfileUserID" ON "ProfileTags" ("UserProfileUserID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260302183314_InitialCreate', '8.0.24');

COMMIT;


